version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started!
      - mvn install
  post_build:
    commands:
      # move the jar (by wildcard, agnostic to its name) to top level app.jar
      - mv target/swagger-spring-1.0.0.jar application.jar
artifacts:
  files:
    # publish the now top level app.jar as the artifact
    - application.jar
