version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started!
      - mvn install
  post_build:
    commands:
      - echo Build completed!
artifacts:
  files:
    - target/swagger-spring-1.0.0.jar
